// <auto-generated by="the Blazor I18n Text compiler" />
namespace BlazorCRUD1.I18nText
{
    public partial class localizer : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"STORE INFO"</summary>
        public string about;

        /// <summary>"Action"</summary>
        public string action;

        /// <summary>"Add New Customer"</summary>
        public string addCustomer;

        /// <summary>"Add New Product"</summary>
        public string addNewProduct;

        /// <summary>"Add Stock"</summary>
        public string addStock;

        /// <summary>"Adjusted Amount"</summary>
        public string adjustedTotalAmount;

        /// <summary>"All Received"</summary>
        public string allDelivery;

        /// <summary>"Adjustment"</summary>
        public string allowAdjust;

        /// <summary>"Back"</summary>
        public string back;

        /// <summary>"Order"</summary>
        public string buy;

        /// <summary>"Cancel"</summary>
        public string cancel;

        /// <summary>"Clear"</summary>
        public string clear;

        /// <summary>"Confirm"</summary>
        public string confirm;

        /// <summary>"CUSTOMER LIST"</summary>
        public string customer;

        /// <summary>"Company"</summary>
        public string customerCompany;

        /// <summary>"Email"</summary>
        public string customerEmail;

        /// <summary>"Name"</summary>
        public string customerName;

        /// <summary>"Phone"</summary>
        public string customerPhone;

        /// <summary>"Delete"</summary>
        public string delete;

        /// <summary>"Delete Product"</summary>
        public string deleteProduct;

        /// <summary>"Item Delivery"</summary>
        public string DeliveryItem;

        /// <summary>"Deposite"</summary>
        public string depositeAmt;

        /// <summary>"Edit"</summary>
        public string edit;

        /// <summary>"Edit Customer Info"</summary>
        public string editCustomer;

        /// <summary>"Edit Product"</summary>
        public string editProduct;

        /// <summary>"English"</summary>
        public string english;

        /// <summary>"Filter"</summary>
        public string filter;

        /// <summary>"斤"</summary>
        public string gin;

        /// <summary>"HOME"</summary>
        public string home;

        /// <summary>"ID"</summary>
        public string ID;

        /// <summary>"In Stock"</summary>
        public string inStock;

        /// <summary>"Delivery"</summary>
        public string itemDelivery;

        /// <summary>"KG"</summary>
        public string kg;

        /// <summary>"LOGIN"</summary>
        public string login;

        /// <summary>"Next"</summary>
        public string next;

        /// <summary>"No Customer Record"</summary>
        public string noCustomer;

        /// <summary>"Not Received"</summary>
        public string noDelivery;

        /// <summary>"No Order Item"</summary>
        public string noItem;

        /// <summary>"No Order Details"</summary>
        public string noOrder;

        /// <summary>"No Active Product"</summary>
        public string noProduct;

        /// <summary>"Order Details"</summary>
        public string orderDetails;

        /// <summary>"Order ID"</summary>
        public string orderID;

        /// <summary>"Order Type"</summary>
        public string orderType;

        /// <summary>"Partial Recevied"</summary>
        public string partialDelivery;

        /// <summary>"Prev"</summary>
        public string prev;

        /// <summary>"PRODUCT LIST"</summary>
        public string product;

        /// <summary>"Details"</summary>
        public string productDetails;

        /// <summary>"Product Name"</summary>
        public string productName;

        /// <summary>"Product Origin"</summary>
        public string productOrigin;

        /// <summary>"Unit Price"</summary>
        public string productPrice;

        /// <summary>"QTY"</summary>
        public string qty;

        /// <summary>"Order Received QTY"</summary>
        public string receivedOrderQty;

        /// <summary>"REGISTER"</summary>
        public string register;

        /// <summary>"Remain Amount"</summary>
        public string remainAmt;

        /// <summary>"Collect QTY"</summary>
        public string remainQty;

        /// <summary>"SALE"</summary>
        public string sale;

        /// <summary>"Save and Return"</summary>
        public string save;

        /// <summary>"Search By Phone"</summary>
        public string searchByPhone;

        /// <summary>"Select"</summary>
        public string select;

        /// <summary>"Order Settled"</summary>
        public string settled;

        /// <summary>"Settle Order"</summary>
        public string settleOrder;

        /// <summary>"Order Status"</summary>
        public string status;

        /// <summary>"Cost"</summary>
        public string stockCost;

        /// <summary>"Stock Date"</summary>
        public string stockDate;

        /// <summary>"QTY"</summary>
        public string stockQTY;

        /// <summary>"Store Address Line 1"</summary>
        public string storeAddressLine1;

        /// <summary>"Store Address Line 2"</summary>
        public string storeAddressLine2;

        /// <summary>"Store Address Line 3"</summary>
        public string storeAddressLine3;

        /// <summary>"Store Bank A/C 1"</summary>
        public string storeBANKAC1;

        /// <summary>"Store Bank A/C 2"</summary>
        public string storeBANKAC2;

        /// <summary>"Store Bank A/C 3"</summary>
        public string storeBANKAC3;

        /// <summary>"Store Email"</summary>
        public string storeEmail;

        /// <summary>"Store Fax"</summary>
        public string storeFax;

        /// <summary>"Display Item/Page"</summary>
        public string storeItemPerPage;

        /// <summary>"Display Lanugage"</summary>
        public string storeLanguage;

        /// <summary>"Store Phone"</summary>
        public string storeLocalPhone;

        /// <summary>"Store Mobile Phone"</summary>
        public string storeMobilePhone;

        /// <summary>"Store Name"</summary>
        public string storeName;

        /// <summary>"Unit"</summary>
        public string storeUnit;

        /// <summary>"Sub Total"</summary>
        public string subTotal;

        /// <summary>"TO"</summary>
        public string to;

        /// <summary>"Total Amount"</summary>
        public string totalAmount;

        /// <summary>"Order Total QTY"</summary>
        public string totalOrderQty;

        /// <summary>"Total Stock"</summary>
        public string totalStock;

        /// <summary>"繁體中文"</summary>
        public string tradChinese;

        /// <summary>"TXN RECORD"</summary>
        public string txnRecord;
    }
}
